name: Validate Commits

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@861b4d9f1085e4038d715c541f02b43784676631
        with:
          configFile: './.commitlintrc.yml'
