name: Markdownlint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Lint files
      uses: articulate/actions-markdownlint@v1
      with:
          files: .
          config: .markdownlint.yaml
